[passwords]
ifscher = "fischer220989"
bob = "password456"
charlie = "password789"

[roles]
ifscher = "admin"
bob = "admin"
charlie = "super-admin"

[names]
ifscher = "Christian Fischer"
bob = "Bob Synclair"
charlie = "Charlie Chaplin"